name: Sync Main to audit-findings branch
# this workflow will sync `main` to `audit-findings`
# due to differences in the current fleek build requirements
# it is necessary to keep the branches separate

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Checkout audit-findings branch
        run: git checkout audit-findings
      - name: Merge main into audit-findings
        run: git merge main --no-ff
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin audit-findings
