# this workflow syncs the ABIs from v1-core to xeon-dapp
name: Sync ABIs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_abis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout v1-core repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash

      - name: Build and Extract ABIs
        run: |
          # Source Foundry environment
          source ~/runner/.bashrc

          # Ensure the script is executable
          chmod +x extract_and_copy_abis.sh

          # Build the project and extract ABIs
          forge build
          ./extract_and_copy_abis.sh

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone xeon-dapp repository
        run: |
          git clone https://github.com/xeon-protocol/xeon-dapp.git
          cd xeon-dapp
          git checkout -B abi/sync || git checkout abi/sync

      - name: Sync ABIs to xeon-dapp
        run: |
          cd xeon-dapp
          cp -r ../v1-core/abi/* src/abi/
          git add abi/
          git commit -m "Sync ABIs from v1-core"
          git push origin abi/sync
