name: Sync ABI Files to xeon-dapp

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  sync-abi-to-dapp:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH for xeon-dapp
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.XEON_DAPP_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa_xeon_dapp
          chmod 600 ~/.ssh/id_rsa_xeon_dapp
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout v1-core repository
        uses: actions/checkout@v3
        with:
          repository: xeon-protocol/v1-core
          path: v1-core
          ssh-key: ${{ secrets.V1_CORE_SSH_PRIVATE_KEY }}
          ref: main

      - name: Checkout xeon-dapp repository
        uses: actions/checkout@v3
        with:
          repository: xeon-protocol/xeon-dapp
          path: xeon-dapp
          ssh-key: ${{ secrets.XEON_DAPP_SSH_PRIVATE_KEY }}
          ref: main

      - name: Create new branch for ABI sync
        run: |
          cd xeon-dapp
          git checkout -b ci/abi-sync

      - name: Copy ABI files
        run: |
          mkdir -p xeon-dapp/src/abi
          cp -r v1-core/abi/* xeon-dapp/src/abi/

      - name: Commit and push changes
        run: |
          cd xeon-dapp
          git add src/abi/*
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git config user.name "v1-core"
            git config user.email "xeon-protocol-actions@github.com"
            git commit -m "ci: sync ABI files from `v1-core`"
            git push origin ci/abi-sync
          fi

      - name: List changed files
        id: changes
        run: |
          cd xeon-dapp
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create Pull Request
        if: env.CHANGED_FILES != ''
        run: |
          PR_URL=$(gh pr create \
            --repo xeon-protocol/xeon-dapp \
            --head ci/abi-sync \
            --base main \
            --title '[v1-core]: sync ABI files' \
            --body "$(echo -e 'gm ☀️\n\nhere are some incoming ABI changes from the `v1-core` repository\n\n**Summary of changes:**\n${{ env.CHANGED_FILES }}\n\nPlease review the changes to ensure there are no breaking changes before merging.')" \
            --label "automated,scope: contracts" \
            --reviewer "RTJ99" \
            --assignee "heyJonBray" \

        env:
          GH_TOKEN: ${{ secrets.SYNC_TOKEN }}
